#! /bin/bash

export EDITOR=nvim

source <(fzf --zsh)
source <(zoxide init zsh --cmd cd)
source <(starship init zsh)
# Variables
PROJECT_PATH_PYTHON="/home/mavenried/Projects/python/"
PROJECT_PATH_LUA="/home/mavenried/Projects/lua"
PROJECT_PATH_RUST="/home/mavenried/Projects/rust"
PROJECT_PATH_SCRIPTS="/mnt/DATA/scripts"

eval "$(proj-cmd init zsh)"

PATH=$PATH:"./bin:/home/mavenried/.local/bin:$PROJECT_PATH_SCRIPTS"

mav() {
  macchina --theme mavenried -o host -o machine -o processor -o distribution -o processor-load -o battery
}

bak() {
  for f in "$@"; do
    if [[ "$f" == *.bak ]]; then
      target="${f%.bak}"
      if [[ -e "$target" ]]; then
        echo "Skipping $f: $target already exists"
      else
        mv -- "$f" "$target"
      fi
    else
      if [[ -e "$f.bak" ]]; then
        echo "Skipping $f: $f.bak already exists"
      else
        mv -- "$f" "$f.bak"
      fi
    fi
  done
}

index() {
  if [[ "$1" == "" ]]; then
    dir=$(pwd)
  else
    dir=$1
  fi
  echo "Opening $dir/indexer.json in nvim..."
  nvim "$dir/indexer.json"
}

config() {
  nvim "/mnt/DATA/dots/$1"
}

clean() {
  files=$(fd target /mnt/DATA/Projects/rust/ -t d -u)
  if [[ "$files" == "" ]]; then
    printf "\x1b[31mNothing to clean.\x1b[0m\n"
  else
    printf "\x1b[33mFound the following directories:\n\x1b[31m%s\n\x1b[0m" "$files"
    if gum confirm --default=false "Do you want to delete these directories?"; then
      echo "deleting..."
      gum spin --title="Removing..." -- fd target /mnt/DATA/Projects/rust/ -t d -u --exec rm -fr {}
    fi
  fi

}

open() {
  for file in "$@"; do
    xdg-open "$file"
  done
}

mkcd() {
  mkdir -p "$1"
  cd "$1" || return 1
}

# Call mav once
mav

# Plugin init
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Aliases
alias zel="zellij -l welcome"
alias clear="printf '\x1B[H\x1B[2J\x1B[3J';"
alias pip="python3 -m pip --break-system-packages"
alias ls="eza -l"
alias indexer="python3 $PROJECT_PATH_PYTHON/Indexer/main.py"
alias lyrics="playerctl --format=\"{{artist}};{{title}}\" metadata | lyrics.py"
alias mkdate="mkcd $(date +%d%m%y)"

alias gc="git commit"
alias gp="git push -u origin main"
alias gac="git add . && git commit"
alias gacp="git add . && git commit && git push -u origin main"
alias install="yes|yay -S"
alias uninstall="yay -R"
alias update="yes | yay -Syu"
alias lsa="eza -la"
alias q=exit
alias icat="kitten icat"
alias pls=sudo
alias btop="btop --force-utf"
alias ppc=powerprofilesctl
alias bkp="rsync -aAX --delete --info=progress2 /mnt/DATA/ /run/media/mavenried/MavenDATA"
