background {
    monitor =
  #path = $HOME/Pictures/CURRENT
    path = screenshot
    blur_passes = 1
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}
shape {
    monitor =
    size = 600, 800
    color = rgba(40, 40, 40, 1)
    rounding = 90
    rotate = 0
    xray = false

    position = -500, 0
    halign = center
    valign = center
    border_color = rgb(689d6a)
    border_size = 1
 }
shape {
    monitor =
    size = 400, 600
    color = rgba(40, 40, 40, 1)

    border_color = rgb(b16286)
    border_size = 1

    rounding = 90
    rotate = 0
    xray = false

    position = 500, 0
    halign = center
    valign = center
}
shape {
    monitor =
    size = 72, 30
    color = rgba(40, 40, 40, 1)

    border_color = rgb(689d6a)
    border_size = 1

    rounding = 90
    rotate = 0
    xray = false

    position = -5, -7
    halign = right
    valign = top
}
label {
    monitor =
    text = cmd[update:5000] /home/maverikio/projects/scripts/battery
    color = rgb(689d6a)
    font_size = 12
    font_family = JetbrainsMono Nerd Font
    position = -17, -12
    halign = right
    valign = top
    shadow_passes = 5
    shadow_size = 10
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 1
    dots_size = 0.2 
    dots_spacing = 0.2 
    dots_center = true
    dots_rounding = -1
    outer_color = rgb(b16286)
    inner_color = rgba(393939ff)
    font_color = rgb(ebdbb2)
    fade_on_empty = false
    placeholder_text = 
    hide_input = false
    rounding = -1
    check_color = rgba(d7992166)
    fail_color = rgba(fb493466) 
    fail_text =   
    fail_transition = 300 
    capslock_color = rgba(f38ba866)
    numlock_color = -1
    bothlock_color = -1 
    invert_numlock = false 
    swap_font_color = false 
    position = 500, -180
    halign = center
    valign = center
    font_family = JetbrainsMono Nerd Font
}

label {
    monitor =
    text = cmd[update:500] /home/maverikio/projects/scripts/uptime
    color = rgb(458588)
    font_size = 25
    font_family = JetbrainsMono Nerd Font
    position = 490, 200
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}
image {
    path = /home/maverikio/Pictures/AVATAR
    rounding = -1 

    position = 500, 50 
    halign = center
    valign = center
  }

label {
    monitor =
    text = cmd[update:1000] date +%I
    color = rgb(d3869b)
    font_size = 250
    font_family = JetbrainsMono Nerd Font
    position = -500, 150
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}

label {
    monitor =
    text = cmd[update:1000] date +%M
    color = rgb(8ec07c)
    font_size = 250
    font_family = JetbrainsMono Nerd Font
    position = -500, -150
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}

label {
    monitor =
    text = $USER
    color = rgba(ebdbb2)
    font_size = 30
    font_family = JetbrainsMono Nerd Font
    position = 500, -100
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}

