general { 
    gaps_in = 5
    gaps_out = 5
    border_size = 2

    col.active_border = $hl
    col.inactive_border = $unfocused_border_color

    resize_on_border = true 
    allow_tearing = false

    layout = scrolling
    extend_border_grab_area = 2
}

decoration {
    rounding = 10 

    active_opacity = 1
    inactive_opacity = 0.9
    blur {
        enabled = true
        size = 1
        passes = 3
        vibrancy = 0.1696
    }
}

animations {
    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = easeOutBack,  0.175, 0.885, 0.32, 1.275

    animation = windows, 1, 7, myBezier, slide top
    animation = windowsOut, 1, 7, myBezier, slide bottom
    animation = fade, 1, 7, default
    animation = workspaces, 1, 5, default, slidevert
}

dwindle {
    pseudotile = true
    preserve_split = true 
}

