# Blood Choco — deep dark crimson
bgd0 = "#0b0708"
bgd1 = "#130d0f"
bgd2 = "#1c1214"
bgd3 = "#301a1e"
bgd4 = "#4a262c"
txt1 = "#f4eaea"
txt2 = "#c7a9ad"
acct = "#e03050"
srch = "#4a262c"
btns = "#ffffff"
